POST http://localhost:5000/api/users/register
Content-Type: application/json

{

  "name": "John Doe",
  "email": "john4@example.com",
  "password": "Password123",
  "phone": "123456789",
  "city": "New York",
  "age": 30,
  "gender": "male",
  "role": "manager"
}

###

POST http://localhost:5000/api/users/login
Content-Type: application/json

{
    "email": "john4@example.com",
  "password": "Password123"

}

###

GET http://localhost:5000/api/users/users

###

POST http://localhost:5000/api/products/addProduct
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3NWZkMWE0YWFjMWY4Mjk2ZjBkOTlmMSIsImlhdCI6MTczNDMzMjg3MywiZXhwIjoxNzM0NDE5MjczfQ.VSbB-X7EQZnXnVqpEAeBNXA0yYMVECVd5YDPbMRx08M

{
  "name": "milk2",
  "image": "https://example.com/images/gaming-laptop.jpg",
  "price": 2500,
  "category": "Electronics",
  "description": "A high-performance laptop for gaming and professional use."
}



### 

POST http://localhost:5000/api/meals/addMeal
    Content-Type: application/json

{
"title": "Chicken Salad", "description": "A healthy salad with grilled chicken.", "price": 15.99, "image": "https://example.com/images/chicken-salad.jpg", "category": "Salads", "Ingredients": [

{
"ingredient": "Chicken", "quantity": "200g"
}, {

"ingredient": "Lettuce", "quantity": "100g"
}, {

"ingredient": "Tomato", "quantity": "50g"
}, {

"ingredient": "Cucumber", "quantity": "50g"
}

]

}

### 
GET http://localhost:5000/api/meals/getAllMeals

###

DELETE http://localhost:5000/api/meals/deleteMeal/675fedc02af5720663d4eedb

###

PUT http://localhost:5000/api/meals/changeMeal/675ff3b03787a1cb3383c560

 Content-Type: application/json

{
"title": "Chicken Salad",
 "description": "A healthy salad with grilled chicken.",
  "price": 34.99,
   "image": "https://example.com/images/chicken-salad.jpg",
    "category": "Salads", "Ingredients": [

{
"ingredient": "Chicken", "quantity": "400g"
}, {

"ingredient": "Lettuce", "quantity": "100g"
}, {

"ingredient": "Tomato", "quantity": "50g"
}, {

"ingredient": "Cucumber", "quantity": "50g"
}

]

}