POST http://localhost:5000/api/bons/addBon
Content-Type: application/json

{
  "branch": "676e884378317a74ac0817b2",
  "user": "676d0974ccb270069df3e06f",
  "meals": [
    {
      "meal": "677690cbbcdd3093b1ca96e9",
      "quantity": 2,
      "note": "Extra spicy"
    },
    {
      "meal": "67769729bcdd3093b1ca990d",
      "quantity": 1,
      "note": "No onions"
    }
  ],
  "tableNumber": 4
}

###
GET http://localhost:5000/api/bons/allBons

###
PUT http://localhost:5000/api/bons/updateBon/676e8b9bfa05ce7def1f2066
Content-Type: application/json

{
  "branch": "676e884378317a74ac0817b2",
  "user": "676d0974ccb270069df3e06f",
  "meals": [
    {
      "meal": "67672a1939cb7bdf4c03f9ae",
      "quantity": 2,
      "note": "Extra spicy"
    },
    {
      "meal": "676aa582b08100a707be237e",
      "quantity": 1,
      "note": "No onions"
    }
  ],
  "shift": "6772d5c9735b56ed5974f385",
  "tableNumber": 4
}
###
GET http://localhost:5000/api/bons/allBons

###
DELETE http://localhost:5000/api/bons/deleteBon/6771069a535c2367fbfdccd1

###
PUT http://localhost:5000/api/bons/updateDeliveredBon/6773ba2b8f8d42d3775831e3

###
PUT http://localhost:5000/api/bons/updateReadyBon/6773ba2b8f8d42d3775831e3

###
PUT http://localhost:5000/api/bons/updatePaidBon/6773ba2b8f8d42d3775831e3

