POST http://localhost:5000/api/branches/addBranch
Content-Type: application/json

{
    {
  "branchName":"Tel Aviv Branch",
  "address": "Dizengoff St 100, Tel Aviv",
  "tables": [
    { "tableNumber": 1, "seats": 4 },
    { "tableNumber": 2, "seats": 4 },
    { "tableNumber": 3, "seats": 6 },
    { "tableNumber": 4, "seats": 6 },
    { "tableNumber": 5, "seats": 2 },
    { "tableNumber": 6, "seats": 4 },
    { "tableNumber": 7, "seats": 8 },
    { "tableNumber": 8, "seats": 10 }
  ],
}

}