POST http://localhost:5000/api/branches/addBranch
Content-Type: application/json

    {
  "branchName":"holon Branch",
  "address": "Dizengoff St 100, Tel Aviv",
  "tables": [
    { "tableNumber": 1, "seats": 1 },
    { "tableNumber": 2, "seats": 2 },
    { "tableNumber": 3, "seats": 3 },
    { "tableNumber": 4, "seats": 4 },
    { "tableNumber": 5, "seats": 5 },
    { "tableNumber": 6, "seats": 6 },
    { "tableNumber": 7, "seats": 7 },
    { "tableNumber": 8, "seats": 8 }
  ]
}

###

GET http://localhost:5000/api/branches/allBranches

###

GET http://localhost:5000/api/branches/getBranch/

###

PUT http://localhost:5000/api/branches/updateBranch/6763ea1d3745860377c67200
Content-Type: application/json

    {
  "branchName":"Tel Aviv Branch",
  "address": "Dizengoff St 100, Tel Aviv",
  "tables": [
    { "tableNumber": 1, "seats": 8 },
    { "tableNumber": 2, "seats": 2 },
    { "tableNumber": 3, "seats": 6 },
    { "tableNumber": 4, "seats": 6 },
    { "tableNumber": 5, "seats": 2 },
    { "tableNumber": 6, "seats": 4 },
    { "tableNumber": 7, "seats": 8 },
    { "tableNumber": 8, "seats": 10 },
    { "tableNumber": 9, "seats": 10 }
  ]
}

###

DELETE http://localhost:5000/api/branches/deleteBranch/6763e0115b04a26149d59221

###

PUT http://localhost:5000/api/branches/addTable
Content-Type: application/json

{
    "branchId":"6763ea1d3745860377c67200",
    "tableNumber":12,"seats":8

}

###

PUT http://localhost:5000/api/branches/updateTableSeats
Content-Type: application/json

{
    "branchId":"6763ea1d3745860377c67200",
    "tableNumber":10,"newSeats":6

}


###

GET http://localhost:5000/api/branches/allBranches
###

DELETE http://localhost:5000/api/branches/deleteTable
Content-Type: application/json

{
    "branchId":"6763ea1d3745860377c67200",
    "tableNumber":10

}

