POST http://localhost:5000/api/users/register
Content-Type: application/json

{
  "name": "test2",
  "email": "test2@mail",
  "password": "1234",
  "phone": "123456789",  
  "gender": "male",
  "role": "manager"
}

###

POST http://localhost:5000/api/users/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "Password123"
}

###

GET http://localhost:5000/api/users/users

###

PUT http://localhost:5000/api/users/updateUser/67692d930b1a41029ccf5cea
Content-Type: application/json

{
  "name": "John Doe2"
}

###

DELETE http://localhost:5000/api/users/deleteUser/67691b6a8648ba7de0a87753