POST http://localhost:5000/api/users/register
Content-Type: application/json

{
  "name": "test2",
  "email": "test2@mail",
  "password": "1234",
  "phone": "123456789",  
  "gender": "male",
  "role": "manager"
}

###

POST http://localhost:5000/api/users/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "Password123"
}

###

GET http://localhost:5000/api/users/users

###

PUT http://localhost:5000/api/users/updateUser/67692d930b1a41029ccf5cea
Content-Type: application/json

{
  "name": "John Doe2"
}

###

DELETE http://localhost:5000/api/users/deleteUser/67691b6a8648ba7de0a87753

###

PUT http://localhost:5000/api/users/startShift/676d0934ccb270069df3e069
Content-Type: application/json

{
  "branch": "676d0974ccb270069df3e06f",
  "shiftId": "67760e001bc342ef752644fb"
}

###

PUT http://localhost:5000/api/users/endShift/676d0934ccb270069df3e069
Content-Type: application/json

{
  "branchId": "676d0974ccb270069df3e06f",
  "shiftId": "67760e001bc342ef752644fb"
}

###

PUT http://localhost:5000/api/users/endShift/676d0934ccb270069df3e069

###

GET http://localhost:5000/api/users/user/676d07f6ccb270069df3e063

