POST http://localhost:5000/api/users/register
Content-Type: application/json

{
  "name": "test5",

  "email": "test5@example.com",

  "password": "Password123",
  "phone": "123456789",  
  "gender": "male",
  "role": "manager",   
  "branch": "6763ea1d3745860377c67200" 
}

###

POST http://localhost:5000/api/users/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "Password123"
}

###

GET http://localhost:5000/api/users/users

###

PUT http://localhost:5000/api/users/updateUser/67692d930b1a41029ccf5cea
Content-Type: application/json

{
  "name": "John Doe2"
}

###

DELETE http://localhost:5000/api/users/deleteUser/67691b6a8648ba7de0a87753